//
//  ClipboardHistory.swift
//  Squirrel
//

import AppKit
import CryptoKit

enum ClipboardHistoryKind: String, Codable {
  case text
  case image
  case files
}

struct ClipboardHistoryEntry: Codable, Identifiable {
  let id: UUID
  var date: Date
  let kind: ClipboardHistoryKind
  let text: String?
  let imageFileName: String?
  let imagePasteboardType: String?
  let filePaths: [String]?
  let fingerprint: String

  var displayTitle: String {
    func shortened(_ value: String, limit: Int = 24) -> String {
      guard value.count > limit else { return value }
      return String(value.prefix(limit)) + "…"
    }
    switch kind {
    case .text:
      let singleLine = (text ?? "")
        .replacingOccurrences(of: "\n", with: " ")
        .replacingOccurrences(of: "\t", with: " ")
        .trimmingCharacters(in: .whitespacesAndNewlines)
      return singleLine.isEmpty ? "[空文本]" : shortened(singleLine)
    case .image:
      return "[图片]"
    case .files:
      let paths = filePaths ?? []
      if paths.count == 1 {
        return shortened("[文件] \(URL(fileURLWithPath: paths[0]).lastPathComponent)")
      }
      return "[文件] \(paths.count) 项"
    }
  }
}

final class ClipboardHistoryManager {
  private static let retention: TimeInterval = 7 * 24 * 60 * 60
  private static let sensitiveTypes = [
    NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
    NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
    NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
  ]
  private static let imageTypes: [(NSPasteboard.PasteboardType, String)] = [
    (.png, "png"),
    (NSPasteboard.PasteboardType("public.jpeg"), "jpg"),
    (NSPasteboard.PasteboardType("public.heic"), "heic"),
    (.tiff, "tiff")
  ]

  private let fileManager = FileManager.default
  private let pasteboard = NSPasteboard.general
  private let historyDirectory: URL
  private let imageDirectory: URL
  private let indexURL: URL
  private var timer: Timer?
  private var lastChangeCount: Int
  private(set) var entries = [ClipboardHistoryEntry]()

  init() {
    let appSupport = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
    historyDirectory = appSupport
      .appendingPathComponent("Squirrel", isDirectory: true)
      .appendingPathComponent("ClipboardHistory", isDirectory: true)
    imageDirectory = historyDirectory.appendingPathComponent("Images", isDirectory: true)
    indexURL = historyDirectory.appendingPathComponent("history.json")
    lastChangeCount = pasteboard.changeCount
    load()
    purgeExpired()
  }

  func start() {
    guard timer == nil else { return }
    lastChangeCount = pasteboard.changeCount
    timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
      self?.captureIfNeeded()
    }
  }

  func stop() {
    timer?.invalidate()
    timer = nil
  }

  func currentEntries() -> [ClipboardHistoryEntry] {
    captureIfNeeded()
    purgeExpired()
    return entries
  }

  func imageData(for entry: ClipboardHistoryEntry) -> Data? {
    guard let fileName = entry.imageFileName else { return nil }
    return try? Data(contentsOf: imageDirectory.appendingPathComponent(fileName))
  }

  @discardableResult
  func restore(_ entry: ClipboardHistoryEntry) -> Bool {
    let restored: Bool
    switch entry.kind {
    case .text:
      guard let text = entry.text else { return false }
      pasteboard.clearContents()
      restored = pasteboard.setString(text, forType: .string)
    case .image:
      guard let data = imageData(for: entry),
            let rawType = entry.imagePasteboardType else {
        return false
      }
      pasteboard.clearContents()
      restored = pasteboard.setData(data, forType: NSPasteboard.PasteboardType(rawType))
    case .files:
      let urls = (entry.filePaths ?? []).map { NSURL(fileURLWithPath: $0) }
      guard !urls.isEmpty else { return false }
      pasteboard.clearContents()
      restored = pasteboard.writeObjects(urls)
    }
    lastChangeCount = pasteboard.changeCount
    return restored
  }
}

private extension ClipboardHistoryManager {
  func captureIfNeeded() {
    guard pasteboard.changeCount != lastChangeCount else { return }
    lastChangeCount = pasteboard.changeCount
    guard !Self.sensitiveTypes.contains(where: { pasteboard.availableType(from: [$0]) != nil }) else {
      return
    }

    if let paths = filePaths(), !paths.isEmpty {
      addFiles(paths)
      return
    }
    if let image = imageData() {
      addImage(data: image.data, type: image.type, fileExtension: image.fileExtension)
      return
    }
    if let text = pasteboard.string(forType: .string), !text.isEmpty {
      addText(text)
    }
  }

  func filePaths() -> [String]? {
    guard let items = pasteboard.pasteboardItems else { return nil }
    let paths = items.compactMap { item -> String? in
      guard let value = item.string(forType: .fileURL),
            let url = URL(string: value),
            url.isFileURL else {
        return nil
      }
      return url.path
    }
    return paths.isEmpty ? nil : paths
  }

  func imageData() -> (data: Data, type: NSPasteboard.PasteboardType, fileExtension: String)? {
    for (type, fileExtension) in Self.imageTypes {
      if let data = pasteboard.data(forType: type), !data.isEmpty {
        return (data, type, fileExtension)
      }
    }
    return nil
  }

  func addText(_ text: String) {
    let fingerprint = digest(Data(("text\u{0}" + text).utf8))
    add(ClipboardHistoryEntry(
      id: UUID(),
      date: .now,
      kind: .text,
      text: text,
      imageFileName: nil,
      imagePasteboardType: nil,
      filePaths: nil,
      fingerprint: fingerprint
    ))
  }

  func addFiles(_ paths: [String]) {
    let fingerprint = digest(Data(("files\u{0}" + paths.joined(separator: "\u{0}")).utf8))
    add(ClipboardHistoryEntry(
      id: UUID(),
      date: .now,
      kind: .files,
      text: nil,
      imageFileName: nil,
      imagePasteboardType: nil,
      filePaths: paths,
      fingerprint: fingerprint
    ))
  }

  func addImage(data: Data, type: NSPasteboard.PasteboardType, fileExtension: String) {
    let fingerprint = digest(data)
    let fileName = "\(fingerprint).\(fileExtension)"
    do {
      try createDirectories()
      let imageURL = imageDirectory.appendingPathComponent(fileName)
      if !fileManager.fileExists(atPath: imageURL.path) {
        try data.write(to: imageURL, options: .atomic)
      }
      add(ClipboardHistoryEntry(
        id: UUID(),
        date: .now,
        kind: .image,
        text: nil,
        imageFileName: fileName,
        imagePasteboardType: type.rawValue,
        filePaths: nil,
        fingerprint: fingerprint
      ))
    } catch {
      print("Unable to save clipboard image: \(error.localizedDescription)")
    }
  }

  func add(_ entry: ClipboardHistoryEntry) {
    if let duplicate = entries.firstIndex(where: { $0.kind == entry.kind && $0.fingerprint == entry.fingerprint }) {
      let old = entries.remove(at: duplicate)
      if old.kind == .image, old.imageFileName != entry.imageFileName {
        removeImageIfUnused(old.imageFileName)
      }
    }
    entries.insert(entry, at: 0)
    purgeExpired(saveAfterPurging: false)
    save()
  }

  func purgeExpired(saveAfterPurging: Bool = true) {
    let cutoff = Date.now.addingTimeInterval(-Self.retention)
    let expired = entries.filter { $0.date < cutoff }
    guard !expired.isEmpty else { return }
    entries.removeAll { $0.date < cutoff }
    for entry in expired where entry.kind == .image {
      removeImageIfUnused(entry.imageFileName)
    }
    if saveAfterPurging {
      save()
    }
  }

  func removeImageIfUnused(_ fileName: String?) {
    guard let fileName,
          !entries.contains(where: { $0.imageFileName == fileName }) else {
      return
    }
    try? fileManager.removeItem(at: imageDirectory.appendingPathComponent(fileName))
  }

  func load() {
    do {
      let data = try Data(contentsOf: indexURL)
      let decoder = JSONDecoder()
      decoder.dateDecodingStrategy = .millisecondsSince1970
      entries = try decoder.decode([ClipboardHistoryEntry].self, from: data)
        .sorted { $0.date > $1.date }
    } catch let error as NSError where error.domain == NSCocoaErrorDomain &&
        error.code == NSFileReadNoSuchFileError {
      entries = []
    } catch {
      print("Unable to load clipboard history: \(error.localizedDescription)")
      entries = []
    }
  }

  func save() {
    do {
      try createDirectories()
      let encoder = JSONEncoder()
      encoder.dateEncodingStrategy = .millisecondsSince1970
      try encoder.encode(entries).write(to: indexURL, options: .atomic)
    } catch {
      print("Unable to save clipboard history: \(error.localizedDescription)")
    }
  }

  func createDirectories() throws {
    try fileManager.createDirectory(at: imageDirectory, withIntermediateDirectories: true)
  }

  func digest(_ data: Data) -> String {
    SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
  }
}
